name: Release MOD artifacts.

on:
  workflow_dispatch:
  push:
    tags:
      - '[1-9][0-9]+.[0-9]+.[0-9]+(-((RC)|(GA)).[1-9][0-9]*)?'

env:
  DRAFT_TAG_NAME: ''

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: windows-latest

    steps:
      - name: '### チェックアウト ###'
        uses: actions/checkout@v4

      - name: '### 環境変数設定 ###'
        id: set_evn
        run: |
          "DRAFT_TAG_NAME=v$(Get-Date -Format 'yyyy.MM.dd.HHmmss')" >> $env:GITHUB_ENV

      - name: '### リリース ###'
        uses: softprops/action-gh-release@v2.5.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_type == 'tag' && github.ref_name || env.DRAFT_TAG_NAME }}
          draft: ${{ github.event_name == 'workflow_dispatch' }}
          prerelease: ${{ github.event_name == 'workflow_dispatch' }}
          generate_release_notes: ${{ github.ref_type == 'tag' }}
          files: |
            init.bat
            update_all_plugins.bat
